import { Match, Point } from '../types/tennis';

export function createSampleGrandSlamMatch(): Match {
  const match: Match = {
    match_id: 1723500000000,
    players: {
      player_a: { name: 'C. Alcaraz' },
      player_b: { name: 'J. Sinner' },
    },
    match_format: 'best_of_3',
    surface: 'Hard (Plexicushion)',
    date: '2026-08-14',
    notes: 'Final de Torneo ATP Masters 1000 - Registro detallado con Court Detail',
    first_server: 'A',
    is_completed: false,
    winner: null,
    created_at: '2026-08-14T15:00:00.000Z',
    updated_at: '2026-08-14T16:15:00.000Z',
    sets: [
      {
        set_number: 1,
        games: [
          // Game 1 (Alcaraz serves, holds 40-15)
          {
            game_number: 1,
            is_tiebreak: false,
            points: [
              {
                point_id: 101,
                server: 'A',
                returner: 'B',
                serve_side: 'deuce',
                serve_type: 1,
                serve_result: 'ace',
                point_result: 'ace',
                winner: 'A',
                score_before: '0-0',
                point_context: 'regular',
                ball_count: 1,
                start_time: '2026-08-14T15:00:10.000Z',
                end_time: '2026-08-14T15:00:13.000Z',
                duration_ms: 3000,
                derived_serve_zone: 't',
                court_detail: {
                  saque: { bote: { x: 0.46, y: 0.44 } },
                },
              },
              {
                point_id: 102,
                server: 'A',
                returner: 'B',
                serve_side: 'ad',
                serve_type: 1,
                serve_result: 'in_play',
                point_result: 'winner',
                winner: 'A',
                score_before: '15-0',
                point_context: 'regular',
                final_type: 'forehand',
                ball_count: 5,
                start_time: '2026-08-14T15:00:35.000Z',
                end_time: '2026-08-14T15:00:46.000Z',
                duration_ms: 11000,
                derived_serve_zone: 'wide',
                court_detail: {
                  saque: { bote: { x: 0.72, y: 0.42 } },
                  golpe_final: {
                    ejecutor: { x: 0.35, y: 0.85 },
                    destino: { x: 0.75, y: 0.15 },
                  },
                },
              },
              {
                point_id: 103,
                server: 'A',
                returner: 'B',
                serve_side: 'deuce',
                serve_type: 2,
                serve_result: 'in_play',
                point_result: 'return_winner',
                winner: 'B',
                score_before: '30-0',
                point_context: 'regular',
                return_type: 'backhand',
                ball_count: 2,
                start_time: '2026-08-14T15:01:05.000Z',
                end_time: '2026-08-14T15:01:10.000Z',
                duration_ms: 5000,
                derived_serve_zone: 'body',
                court_detail: {
                  saque: { bote: { x: 0.35, y: 0.41 } },
                  devolucion: {
                    restador: { x: 0.25, y: 0.08 },
                    bote: { x: 0.72, y: 0.82 },
                  },
                },
              },
              {
                point_id: 104,
                server: 'A',
                returner: 'B',
                serve_side: 'ad',
                serve_type: 1,
                serve_result: 'in_play',
                point_result: 'unforced_error',
                winner: 'A',
                score_before: '30-15',
                point_context: 'regular',
                final_type: 'backhand',
                ball_count: 7,
                start_time: '2026-08-14T15:01:30.000Z',
                end_time: '2026-08-14T15:01:45.000Z',
                duration_ms: 15000,
                derived_serve_zone: 't',
                court_detail: {
                  golpe_final: {
                    ejecutor: { x: 0.30, y: 0.12 },
                    tiro_errado: { x: 0.82, y: 0.94 },
                  },
                },
              },
              {
                point_id: 105,
                server: 'A',
                returner: 'B',
                serve_side: 'deuce',
                serve_type: 1,
                serve_result: 'in_play',
                point_result: 'winner',
                winner: 'A',
                score_before: '40-15',
                point_context: 'game_point',
                final_type: 'drop_shot',
                ball_count: 9,
                start_time: '2026-08-14T15:02:10.000Z',
                end_time: '2026-08-14T15:02:26.000Z',
                duration_ms: 16000,
                derived_serve_zone: 'wide',
                court_detail: {
                  golpe_final: {
                    ejecutor: { x: 0.60, y: 0.70 },
                    destino: { x: 0.35, y: 0.38 },
                  },
                },
              },
            ],
          },
          // Game 2 (Sinner serves, holds 40-30)
          {
            game_number: 2,
            is_tiebreak: false,
            points: [
              {
                point_id: 106,
                server: 'B',
                returner: 'A',
                serve_side: 'deuce',
                serve_type: 1,
                serve_result: 'ace',
                point_result: 'ace',
                winner: 'B',
                score_before: '0-0',
                point_context: 'regular',
                ball_count: 1,
                start_time: '2026-08-14T15:03:00.000Z',
                end_time: '2026-08-14T15:03:03.000Z',
                duration_ms: 3000,
                derived_serve_zone: 'wide',
                court_detail: {
                  saque: { bote: { x: 0.26, y: 0.43 } },
                },
              },
              {
                point_id: 107,
                server: 'B',
                returner: 'A',
                serve_side: 'ad',
                serve_type: 2,
                serve_result: 'double_fault',
                point_result: 'double_fault',
                winner: 'A',
                score_before: '15-0',
                point_context: 'regular',
                ball_count: 1,
                start_time: '2026-08-14T15:03:25.000Z',
                end_time: '2026-08-14T15:03:27.000Z',
                duration_ms: 2000,
                court_detail: null,
              },
              {
                point_id: 108,
                server: 'B',
                returner: 'A',
                serve_side: 'deuce',
                serve_type: 1,
                serve_result: 'in_play',
                point_result: 'winner',
                winner: 'B',
                score_before: '15-15',
                point_context: 'regular',
                final_type: 'forehand',
                ball_count: 4,
                start_time: '2026-08-14T15:03:50.000Z',
                end_time: '2026-08-14T15:04:00.000Z',
                duration_ms: 10000,
                derived_serve_zone: 't',
                court_detail: {
                  golpe_final: {
                    ejecutor: { x: 0.40, y: 0.88 },
                    destino: { x: 0.72, y: 0.12 },
                  },
                },
              },
              {
                point_id: 109,
                server: 'B',
                returner: 'A',
                serve_side: 'ad',
                serve_type: 1,
                serve_result: 'in_play',
                point_result: 'unforced_error',
                winner: 'A',
                score_before: '30-15',
                point_context: 'regular',
                final_type: 'forehand',
                ball_count: 8,
                start_time: '2026-08-14T15:04:20.000Z',
                end_time: '2026-08-14T15:04:36.000Z',
                duration_ms: 16000,
                derived_serve_zone: 'body',
                court_detail: {
                  golpe_final: {
                    ejecutor: { x: 0.75, y: 0.82 },
                    tiro_errado: { x: 0.85, y: 0.15 },
                  },
                },
              },
              {
                point_id: 110,
                server: 'B',
                returner: 'A',
                serve_side: 'deuce',
                serve_type: 1,
                serve_result: 'in_play',
                point_result: 'forced_error',
                winner: 'B',
                score_before: '30-30',
                point_context: 'regular',
                ball_count: 6,
                start_time: '2026-08-14T15:04:55.000Z',
                end_time: '2026-08-14T15:05:08.000Z',
                duration_ms: 13000,
                court_detail: null,
              },
              {
                point_id: 111,
                server: 'B',
                returner: 'A',
                serve_side: 'ad',
                serve_type: 1,
                serve_result: 'in_play',
                point_result: 'winner',
                winner: 'B',
                score_before: '40-30',
                point_context: 'game_point',
                final_type: 'volley',
                ball_count: 5,
                start_time: '2026-08-14T15:05:30.000Z',
                end_time: '2026-08-14T15:05:42.000Z',
                duration_ms: 12000,
                derived_serve_zone: 'wide',
                court_detail: {
                  golpe_final: {
                    ejecutor: { x: 0.55, y: 0.60 },
                    destino: { x: 0.25, y: 0.22 },
                  },
                },
              },
            ],
          },
          // Game 3 (Break Point converted by Sinner!)
          {
            game_number: 3,
            is_tiebreak: false,
            points: [
              {
                point_id: 112,
                server: 'A',
                returner: 'B',
                serve_side: 'deuce',
                serve_type: 1,
                serve_result: 'in_play',
                point_result: 'winner',
                winner: 'B',
                score_before: '0-0',
                point_context: 'regular',
                final_type: 'forehand',
                ball_count: 6,
                start_time: '2026-08-14T15:06:10.000Z',
                end_time: '2026-08-14T15:06:22.000Z',
                duration_ms: 12000,
                derived_serve_zone: 't',
                court_detail: {
                  golpe_final: {
                    ejecutor: { x: 0.70, y: 0.12 },
                    destino: { x: 0.32, y: 0.88 },
                  },
                },
              },
              {
                point_id: 113,
                server: 'A',
                returner: 'B',
                serve_side: 'ad',
                serve_type: 2,
                serve_result: 'in_play',
                point_result: 'unforced_error',
                winner: 'B',
                score_before: '0-15',
                point_context: 'regular',
                final_type: 'forehand',
                ball_count: 4,
                start_time: '2026-08-14T15:06:40.000Z',
                end_time: '2026-08-14T15:06:48.000Z',
                duration_ms: 8000,
                court_detail: null,
              },
              {
                point_id: 114,
                server: 'A',
                returner: 'B',
                serve_side: 'deuce',
                serve_type: 1,
                serve_result: 'ace',
                point_result: 'ace',
                winner: 'A',
                score_before: '0-30',
                point_context: 'regular',
                ball_count: 1,
                start_time: '2026-08-14T15:07:05.000Z',
                end_time: '2026-08-14T15:07:08.000Z',
                duration_ms: 3000,
                derived_serve_zone: 'wide',
                court_detail: {
                  saque: { bote: { x: 0.28, y: 0.42 } },
                },
              },
              {
                point_id: 115,
                server: 'A',
                returner: 'B',
                serve_side: 'ad',
                serve_type: 2,
                serve_result: 'in_play',
                point_result: 'unforced_error',
                winner: 'B',
                score_before: '15-30',
                point_context: 'regular',
                final_type: 'backhand',
                ball_count: 9,
                start_time: '2026-08-14T15:07:30.000Z',
                end_time: '2026-08-14T15:07:48.000Z',
                duration_ms: 18000,
                derived_serve_zone: 'body',
                court_detail: {
                  golpe_final: {
                    ejecutor: { x: 0.32, y: 0.88 },
                    tiro_errado: { x: 0.18, y: 0.22 },
                  },
                },
              },
              {
                point_id: 116,
                server: 'A',
                returner: 'B',
                serve_side: 'deuce',
                serve_type: 1,
                serve_result: 'in_play',
                point_result: 'return_winner',
                winner: 'B',
                score_before: '15-40',
                point_context: 'break_point',
                return_type: 'forehand',
                ball_count: 2,
                start_time: '2026-08-14T15:08:10.000Z',
                end_time: '2026-08-14T15:08:15.000Z',
                duration_ms: 5000,
                derived_serve_zone: 'body',
                court_detail: {
                  saque: { bote: { x: 0.38, y: 0.44 } },
                  devolucion: {
                    restador: { x: 0.70, y: 0.10 },
                    bote: { x: 0.28, y: 0.78 },
                  },
                },
              },
            ],
          },
          // Current live game 4 (Sinner serves, score 15-30)
          {
            game_number: 4,
            is_tiebreak: false,
            points: [
              {
                point_id: 117,
                server: 'B',
                returner: 'A',
                serve_side: 'deuce',
                serve_type: 1,
                serve_result: 'ace',
                point_result: 'ace',
                winner: 'B',
                score_before: '0-0',
                point_context: 'regular',
                ball_count: 1,
                start_time: '2026-08-14T15:09:00.000Z',
                end_time: '2026-08-14T15:09:03.000Z',
                duration_ms: 3000,
                derived_serve_zone: 't',
                court_detail: {
                  saque: { bote: { x: 0.52, y: 0.44 } },
                },
              },
              {
                point_id: 118,
                server: 'B',
                returner: 'A',
                serve_side: 'ad',
                serve_type: 1,
                serve_result: 'in_play',
                point_result: 'winner',
                winner: 'A',
                score_before: '15-0',
                point_context: 'regular',
                final_type: 'forehand',
                ball_count: 7,
                start_time: '2026-08-14T15:09:25.000Z',
                end_time: '2026-08-14T15:09:40.000Z',
                duration_ms: 15000,
                derived_serve_zone: 'wide',
                court_detail: {
                  golpe_final: {
                    ejecutor: { x: 0.72, y: 0.86 },
                    destino: { x: 0.30, y: 0.14 },
                  },
                },
              },
              {
                point_id: 119,
                server: 'B',
                returner: 'A',
                serve_side: 'deuce',
                serve_type: 2,
                serve_result: 'double_fault',
                point_result: 'double_fault',
                winner: 'A',
                score_before: '15-15',
                point_context: 'regular',
                ball_count: 1,
                start_time: '2026-08-14T15:10:00.000Z',
                end_time: '2026-08-14T15:10:02.000Z',
                duration_ms: 2000,
                court_detail: null,
              },
            ],
          },
        ],
      },
    ],
  };

  return match;
}
